# Generated by Django 6.0.3 on 2026-05-22 19:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricantes',
            fields=[
                ('id_fabricante', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Locais',
            fields=[
                ('id_local', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TiposMotor',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Motores',
            fields=[
                ('id_motor', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('potencia', models.CharField(max_length=30)),
                ('tensao', models.CharField(max_length=30)),
                ('corrente', models.CharField(max_length=50)),
                ('rpm', models.CharField(max_length=40)),
                ('modo_fixacao', models.CharField(max_length=100)),
                ('id_fabricante', models.ForeignKey(db_column='id_fabricante', on_delete=django.db.models.deletion.DO_NOTHING, to='projects.fabricantes')),
                ('id_local', models.ForeignKey(db_column='id_local', on_delete=django.db.models.deletion.DO_NOTHING, to='projects.locais')),
                ('id_tipo', models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.DO_NOTHING, to='projects.tiposmotor')),
            ],
        ),
        migrations.CreateModel(
            name='Manutencoes',
            fields=[
                ('id_manutencao', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('data_manutencao', models.DateField()),
                ('descricao', models.TextField()),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('id_motor', models.ForeignKey(db_column='id_motor', on_delete=django.db.models.deletion.DO_NOTHING, to='projects.motores')),
            ],
        ),
        migrations.CreateModel(
            name='Inspecoes',
            fields=[
                ('id_inspecao', models.AutoField(primary_key=True, serialize=False)),
                ('data_inspecao', models.DateField()),
                ('observacoes', models.TextField()),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('id_motor', models.ForeignKey(db_column='id_motor', on_delete=django.db.models.deletion.DO_NOTHING, to='projects.motores')),
            ],
        ),
    ]
