# Generated by Django 5.2.14 on 2026-06-02 02:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricantes',
            fields=[
                ('id_fabricante', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Locais',
            fields=[
                ('id_local', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TiposMotor',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('senha_temporaria', models.BooleanField(default=True)),
                ('nivel_acesso', models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('USER', 'User')], default='USER', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Motores',
            fields=[
                ('id_motor', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('potencia', models.CharField(max_length=30)),
                ('tensao', models.CharField(max_length=30)),
                ('corrente', models.CharField(max_length=50)),
                ('rpm', models.CharField(max_length=40)),
                ('modo_fixacao', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('id_fabricante', models.ForeignKey(db_column='id_fabricante', on_delete=django.db.models.deletion.CASCADE, to='projects.fabricantes')),
                ('id_local', models.ForeignKey(db_column='id_local', on_delete=django.db.models.deletion.CASCADE, to='projects.locais')),
                ('id_tipo', models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.CASCADE, to='projects.tiposmotor')),
            ],
        ),
        migrations.CreateModel(
            name='Inspecoes',
            fields=[
                ('id_inspecao', models.AutoField(primary_key=True, serialize=False)),
                ('data_inspecao', models.DateField()),
                ('status', models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('EM ANDAMENTO', 'EM ANDAMENTO'), ('CONCLUÍDO', 'CONCLUÍDO')], default='PENDENTE', max_length=50)),
                ('observacoes', models.TextField()),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_motor', models.ForeignKey(db_column='id_motor', on_delete=django.db.models.deletion.CASCADE, to='projects.motores')),
            ],
        ),
    ]
