# Generated by Django 6.0.3 on 2026-03-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricantes',
            name='idade',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fabricantes',
            name='telefone',
            field=models.IntegerField(null=True),
        ),
    ]
