# Generated by Django 6.0.3 on 2026-03-21 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_fabricantes_idade_remove_fabricantes_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locais',
            fields=[
                ('id_local', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TiposMotor',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Motores',
            fields=[
                ('id_motor', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('potencia', models.CharField(max_length=30)),
                ('tensao', models.CharField(max_length=30)),
                ('corrente', models.CharField(max_length=50)),
                ('rpm', models.CharField(max_length=40)),
                ('modo_fixacao', models.CharField(max_length=100)),
                ('id_fabricante', models.ForeignKey(db_column='id_fabricante', on_delete=django.db.models.deletion.DO_NOTHING, to='projects.fabricantes')),
                ('id_local', models.ForeignKey(db_column='id_local', on_delete=django.db.models.deletion.DO_NOTHING, to='projects.locais')),
                ('id_tipo', models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.DO_NOTHING, to='projects.tiposmotor')),
            ],
        ),
        migrations.CreateModel(
            name='Manutencoes',
            fields=[
                ('id_manutencao', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('data_manutencao', models.DateField()),
                ('descricao', models.TextField()),
                ('id_motor', models.ForeignKey(db_column='id_motor', on_delete=django.db.models.deletion.DO_NOTHING, to='projects.motores')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='projects.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Inspecoes',
            fields=[
                ('id_inspecao', models.AutoField(primary_key=True, serialize=False)),
                ('data_inspecao', models.DateField()),
                ('observacoes', models.TextField()),
                ('id_motor', models.ForeignKey(db_column='id_motor', on_delete=django.db.models.deletion.DO_NOTHING, to='projects.motores')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='projects.usuarios')),
            ],
        ),
    ]
