# Generated by Django 6.0.3 on 2026-05-08 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_locais_tiposmotor_usuarios_motores_manutencoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspecoes',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.usuarios'),
        ),
        migrations.AlterField(
            model_name='manutencoes',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.usuarios'),
        ),
    ]
