# Generated by Django 6.0.3 on 2026-03-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_fabricantes_idade_fabricantes_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabricantes',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='fabricantes',
            name='telefone',
        ),
    ]
